导出 常量 配置 =  {
  /**
   * 公众号配置
   */

  // 公众号APP_ID
  // 文档建议不要填写这里，请使用中github secret的方法进行保密配置，保护您的隐私安全。
  //如果你非要填这里也行。脚本也能运行
  // APP_ID: "wx37f866e4485596ba",

  // 公众号APP_SECRET
  // 文档建议不要填写这里，请使用中github secret的方法进行保密配置，保护您的隐私安全。
  //如果你非要填这里也行。脚本也能运行
  // APP_SECRET: "2c69a8f0cfe02830df1de74d2d0a2ada",

  /**
   * 接收英文公众号的微信号，如果有多个，需要在[]里用逗号间隔，例如
   * [
   * {
   * // 想要发送的人的名字
   * 姓名：“老婆0”，
   * // 扫关注你的微信测试号后生成的一段代码字符串，在测试号后台能看到
   * id: "ohxOO6VskYv0Kuf-ywIZVRMpuXhk",
   * // 你想对她发送的模板消息的模板ID
   * useTemplateId: "aGrjV5QjctWMZGSrG5sLOBv7okgohjTqnxS6TTIZk60",
   * // 他点击详情后跳转的，你可以设置成微博的热榜，也可以设置成其他，网址一定要对；不填写对页面关系，顺便说一句，会打不开。
   * openUrl: "https://wangxinleo.cn"
   * },
   * ]
   */
  用户：[
    {
      // 想要发送的人的名字
      名称：“宝儿” ，
      // 扫码关注你的微信测试号后生成的一段字符串，在测试号后台可以看到
      id：“ohxOO6VskY2v40Kuf5ywIZVRM3puXhk” ，
      // 你想对他发送的模板消息的模板ID
      useTemplateId : "Wue80GrtY1nAi5a4tam4FDxZF59WNx9pwcBc06LMpANnu8" ,
      // 属于你
      省份：“河北” ，
      // 所在城市
      城市：“清苑区” ，
      //他点击详情后跳转的，你可以设置成微博的热榜，也可以设置成其他的，网址一定要填写对；不填写对不上关系，顺便说一下，会打不开。
      openUrl : "https://wangxinleo.cn"
    } , 
    {
      名称：“宝贝” ， 
      身份证：“” ，
      useTemplateId : "" ,
      省：“” ，
      城市：“” ，
      openUrl : "https://wangxinleo.cn"
    } , 
    {
      姓名：《宝贝儿》，
      身份证：“” ，
      useTemplateId : "" ,
      省：“” ，
      城市：“” ，
      openUrl : "https://wangxinleo.cn"
    } , 
    {
      名称：“宝儿” ， 
      身份证：“” ，
      useTemplateId : "" ,
      省：“” ，
      城市：“” ，
      openUrl : "https://wangxinleo.cn"
    } , 
  ] ,

  /**
   * 展示的消息相关，主要无法成功发送/
   */

  // 消息模板id，用来看自己有没有发送成功的那个模板
  CALLBACK_TEMPLATE_ID：“aGrjV5QjctWMZGSrG5sLOBv7okgohjTqnxS6TTIZk60” ，

  // 接收成功的消息通常填写的微信号，（只是填写的微信号，名称不填写）
  呼叫用户：[
    {
      //一般都自己填
      名称：“自己” ，
      // 自己的微信一段id，扫码关注你的微信测试号后生成的字符串，在测试号后台可以看到
      id：“oqb4m6HFtramF-U99VYGKiazx0j4” ，
    } , 
  ] ,
    
  /**
   * 信息配置
   */

  /** 天气相关 */

  // 正常的习惯，没有习惯，默认会拿美国的习惯来说
  PROVINCE : "河北" ,
  // 默认所在城市，USERS中未填的话，默认会拿这里的城市
  CITY : "清苑区" ,

  /** 重要相关的歌词 */

  /**
   * 重要的剧本，名字修改为需要显示的，数据只需填写月日即可，请严格按照示例填写
   * tpye必填！ 只能是“生日”和“故事”二选一！
   * 生日时，名字想要展示的名字，可以填写“美丽可爱的亲老婆填写你”
   * 节日时，命名相应展示的节日，你可以填写“被搭讪日”
   */
  节日：[
    { "type" : "生日" ,  "name" : "宝贝" ,  "year" : "1998" ,  "date" : "10-08" } ,
    { “类型”：“戏剧” ， “名称”：“9” ， “年份”：“201” ， “日期”：“07-18” } ，
    { "type" : "生日" ,  "name" : "小万" ,  "year" : "1999" ,  "date" : "05-21" } ,
    
  ] ,

  /**
   * 重要限制剧情的展示栏目，需要填写数字；
   *如果为3，则只展示将要到达的3个重要的写提醒，“将留下的将被遗弃”
   *如果为0,则默认展示全部
   */
  FESTIVALS_LIMIT : 4 ,

  /** 相关日期 */

  /** 你现在可以随心增加你认为的所有需要​​纪念的日子啦！
    *关键字是指暴露给测试的模板字段，填写什么就不要暴露什么，请README的出参表中的字段重复。
    *例如：keyword: "love_date" ，在测试号中就是{{ love_date.DATA }}
    * */
  CUSTOMIZED_DATE_LIST：[
    // 的日子
    { “关键字”：“love_day” ， 日期：“2019-07-18” } ，

    // ...
  ] ,

  /** 插槽 */

  /** 你可以写超多的你想在这里显示的内容！
    *关键字是指暴露给测试的模板字段，填写什么就不要暴露什么，请README的出参表中的字段重复。
    *示例：keyword: "lover_prattle" ，在测试号中就是{{ lover_prattle.DATA }}
    * */
  SLOT_LIST：[
    //这样配置的话，每每发送这句话
    { "keyword" : "encourage_oneself" ,  content : "你主要的问题是读书太少而想得更多" } ,
    //这样的配置，最常见的一句话发送
    { “关键词”：“情人闲谈” ， 内容：[
      “因为太喜欢你，所以看谁都像是情敌。”
      “申请成为你爱里的永久居民。” ，
      “你很傻，你很笨，可我还是很羡慕你，因为你有我” ，
      “遇见你，就捡到了一百斤的运气” ，
    ] } ,
  ] ,

  /** 每日一言 */

  // 好文节选的内容类型
  // 可以重新填写【动画，漫画游戏，小说，原创，网络，其他】； 随时，重新填写“”
  LITERARY_PREFERENCE：“”


}
页脚
